# frozen_string_literal: true

require 'minitest/test_task'
require 'rubocop/rake_task'

Minitest::TestTask.create do |t|
  # Have to specify `[0-9][0-9][0-9][0-9]` instead of `**` as the latter would also match the cached gem directory
  # created by `ruby/setup-ruby@v1` action.
  t.test_globs = %w[[0-9][0-9][0-9][0-9]/**/test/**/*_test.rb]
end
RuboCop::RakeTask.new

task default: %i[test rubocop]
