name: CI

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  crystal:
    name: CI - Crystal
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: solutions/crystal
    steps:
      - uses: actions/checkout@v4
      - name: Set up Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Run tests
        run: find . -name '*_spec.cr' -exec crystal spec --order=random {} +
      - name: Run solutions
        run : find . -name main.cr -print0 | sort -z | xargs -0 -i crystal run {}
      - name: Check formatting
        run: crystal tool format --check
  elixir:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: solutions/elixir
    name: CI - Elixir
    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '27.2'
          elixir-version: '1.17.3'
      - name: Run tests
        run: elixir -e 'ExUnit.start()' -r '**/*_test.exs'
      - name: Check formatting
        run: mix format --check-formatted
      - name: Run solutions
        run: find . -name main.exs -print0 | sort -z | xargs -0 -i elixir {}
  nim:
    name: CI - Nim
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: solutions/nim
    steps:
      - uses: actions/checkout@v4
      - name: Set up Nim
        uses: jiro4989/setup-nim-action@v2
      - name: Run tests
        run: find . -name '*_test.nim' -print0 | sort -z | xargs -0 -i nim r {}
      - name: Run solutions
        run : find . -name main.nim -print0 | sort -z | xargs -0 -i nim r {}
      - name: Check formatting
        run: |
          find . -name '*.nim' -exec nimpretty --maxLineLen:100 {} +
          git diff --exit-code
  ruby:
    name: CI - Ruby
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: solutions/ruby
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: solutions/ruby
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake test
      - name: Run solutions
        run : find . -name main.rb -print0 | sort -z | xargs -0 -i ruby {}
      - name: Check linting and formatting
        run: bundle exec rake rubocop
